
# [START app_yaml]
runtime: nodejs
env: flex

beta_settings:
  use_endpoints_api_management: true

endpoints_api_service:
  name: blur-api.endpoints.blur-api.cloud.goog
  config_id: 2016-12-29r1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
# [END app_yaml]